USE DB_BIBLIOTECA;
GO

-- SpInsertar préstamos
CREATE OR ALTER PROCEDURE BIBLIOTECA.sp_InsertarPrestamo
    @CODIGO_USUARIO INT,
    @CODIGO_EJEMPLAR INT,
    @FECHA_PRESTAMO DATETIME,
    @FECHA_DEVOLUCION DATETIME
AS
BEGIN
    INSERT INTO BIBLIOTECA.PRESTAMO (CODIGO_USUARIO, CODIGO_EJEMPLAR, FECHA_PRESTAMO, FECHA_DEVOLUCION)
    VALUES (@CODIGO_USUARIO, @CODIGO_EJEMPLAR, @FECHA_PRESTAMO, @FECHA_DEVOLUCION);
END;
GO

-- SpConsultar libros
CREATE OR ALTER PROCEDURE BIBLIOTECA.sp_ConsultarLibros
    @ISBN VARCHAR(20) = NULL,
    @TITULO VARCHAR(255) = NULL
AS
BEGIN
    SELECT * FROM BIBLIOTECA.LIBRO
    WHERE (@ISBN IS NULL OR ISBN = @ISBN)
    AND (@TITULO IS NULL OR TITULO LIKE '%' + @TITULO + '%');
END;
GO

-- SpActualizar autores
CREATE OR ALTER PROCEDURE BIBLIOTECA.sp_ActualizarAutor
    @CODIGO INT,
    @NOMBRE VARCHAR(100)
AS
BEGIN
    UPDATE BIBLIOTECA.AUTOR
    SET NOMBRE = @NOMBRE
    WHERE CODIGO = @CODIGO;
END;
GO

-- SpBorrar estudiantes
CREATE OR ALTER PROCEDURE BIBLIOTECA.sp_BorrarEstudiante
    @CODIGO_USUARIO INT
AS
BEGIN
    DELETE FROM BIBLIOTECA.USUARIO
    WHERE CODIGO_USUARIO = @CODIGO_USUARIO;
END;
GO

